version: '3'
services:
  opentts:
    image: synesthesiam/opentts:nl
    ports:
      - 5500:5500
  kafka:
    image: confluentinc/confluent-local:7.6.0
    ports:
      - "8082:8082"
      - "9092:9092"
      - "9101:9101"
  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ollama:/root/.ollama
    container_name: ollama2

volumes:
  ollama: